### ISSUE TITLE
Admin-side - vis korrekt antal sale

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger-controller#180]
"Sale" viser i dag antal konferencer, så sale med lyttere på, men hvor der ikke transmitteres fra, tælles med.
Det bør ændres til kun at tælle konferencer der er "Marked'. (se 'confbridge list' herunder)
Herved vises det antal sale der reelt transmitteres fra.

> asterisk -rx 'confbridge list'  
BridgeName               Users   Marked Locked?
================================ ====== ====== ========
47-6800                              2      1    unlocked
45-8850                            12      1    unlocked
45-4700                              6      1    unlocked
47-1357                              1      0    unlocked
45-7500                              1      1    unlocked
46-12745-2                         1      1    unlocked

**Comment by michaelkrog** [comment]
Flyttet til https://github.com/DRB-IT/blacktiger-admin/issues/2
