### ISSUE TITLE
Logout-login ignorerer nye credentials

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger-controller#181]
Hvis man logger ud og derefter logger ind med en anden sals credentials, er det stadig den første sal man er logget ind som.

Hvis man lukker browseren efter logout, virker det ok. Set på både IE11 or Chrome.

Det er selvfølgelig ikke så mange der vil blive ramt af det i praksis, men de der har flere sale kan få lidt problemer under setup hvis de tester flere sales login på samme pc.

**Comment by michaelkrog** [comment]
Det skyldes en fejl i blacktigerjs. Issue oprettet deri: https://github.com/DRB-IT/blacktigerjs/issues/9.
