### ISSUE TITLE
Strip whitespace omkring brugernavn og kodeord

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger-controller#182]
En del har problemer med login når de copy/paster kodeord fra de mails der sendes ud. Man kunne hjælpe dem ved at strippe første og sidste whitespace fra kodeordet.

Det samme gælder egenligt brugernavnet.

**Comment by michaelkrog** [comment]
Fikset med https://github.com/DRB-IT/blacktigerjs/issues/5
