### ISSUE TITLE
Minutælles glemmes når browser genstartes

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger-controller#184]
Jeg er i tvivl om dette har virket før, men det kan i hvert fald forbedres.
Minuttæller for igangværende opkald starter fra nul når browseren har været lukket.
Men blacktiger burde vide hvor længe kaldet har varet, og kan aflevere varigheden til blacktiger-web ved start af browser.

**Comment by michaelkrog** [comment]
Det er nu fikset i blacktigerjs – men tidsstemplet der sendes fra serveren er ikke korrekt. 
Afventer https://github.com/DRB-IT/blacktiger/issues/115

**Comment by michaelkrog** [comment]
DRB-IT/blacktiger#115 er nu fikset.
