### ISSUE TITLE
Mindre "intrusive" besked om mistet forbindelse

### ISSUE THREAD

**Issue by michaelkrog** [DRB-IT/blacktiger-controller#191]
@paf FYI

Beskeden om at forbindelsen er mistet tager meget fokus og kræver en handling fra personen ved mikseren.

Det er fint med info, men blacktiger-controller bør måske ikke afkræve en handling. Det kunne istedet selv forsøge med et interval at oprette forbindelsen igen. Det vil medføre at man, steder hvor man har udfald måske flere gange under mødet, kan nøjes med at blive informeret om at der er udfald og kort efter(forhåbentlig) at forbindelsen er genoptaget.

**Comment by xToMMeRx** [comment]
Helt enig.

Hvis vi pga. en fejl bliver nød til at genstarte blacktiger-controller skal brugerne idag aktivt trykke ok til fejlbeskeden OG huske at refreshe websiden.

Måske det er muligt I det tilfælde at få browseren til selv at forsøge at genskabe forbindelsen igen, eller selv at refreshe browseren så brugerne ikke skal huske at trykke F5 for at få valide data igen?

Der skal selvfølgelig stadig være en eller anden form for information, så brugerne ved at der er et problem.

**Comment by michaelkrog** [comment]
Afventer https://github.com/DRB-IT/blacktigerjs/issues/20

**Comment by michaelkrog** [comment]
@paf Denne ændring kræver en ændring af teksten i GENERAL.LOST_CONNECTION.

Det er ikke længere en alert der kræver at brugeren skal reloade siden. Applikationen vil nu selv forsøge at genskabe forbindelsen. Jeg har lavet en "jumbotron" ligesom når der er én der gerne vil svare, som vises imens applikationen forsøger at genskabe forbindelsen.

Se følgende billeder.

### Med forbindelse
![skaermbillede 2015-05-21 kl 13 23 17](https://cloud.githubusercontent.com/assets/681472/7747618/95c098dc-ffbc-11e4-9bf2-aebd5ffb08ea.png)

### Uden forbindelse
![skaermbillede 2015-05-21 kl 13 20 32](https://cloud.githubusercontent.com/assets/681472/7747607/81c45378-ffbc-11e4-9f00-a8e057582b5f.png)

**Comment by paf61** [comment]
Fin løsning, jeg får lavet noget oversættelse.

**Comment by paf61** [comment]
Skal der måske være en sekundtæller eller lignende så man ved at siden ikke er frosset?

**Comment by michaelkrog** [comment]
Jo, det vil være en fin ting at have. Den forsøger at reconnecte for hver 10 sekunder, så laver en tæller der viser den nedtælling.

**Comment by paf61** [comment]
Oversættelserne er på plads nu.
