### ISSUE TITLE
Brugerflade viser nogle steder engelsk brugerflade istedet for dansk

### ISSUE THREAD

**Issue by michaelkrog** [DRB-IT/blacktiger-controller#195]
I Aalborg har vi Windows Vista og Chrome. Når vi åbner blacktiger-controller vises brugerfladen på engelsk selvom OS'et er dansk.

I Nørresundby lader det til at være det samme de oplever, men jeg aner dog hverken hvilken browser eller OS de har.

**Comment by xToMMeRx** [comment]
Hvilket sprog er Chrome brugerfladen?
Jeg har bemærket at i Chrome følger sprogvælgeren det sprog som Chrome har.

**Comment by michaelkrog** [comment]
Hmm.   Godt spørgsmål. Måske jeg lige skulle tjekke det. :)

Jeg gik blot naivt ud fra at Chrome installeret på en Dansk Vista som
standard ville være dansk og at ingen i Rigssalen ville pille ved det. Men
det er nok lige at skrue lidt for højt op for konklusionsmotoren. :-P

2015-01-25 18:55 GMT+01:00 xToMMeRx <notifications@github.com>:
