### ISSUE TITLE
Minuttælleren på lytterne viser negative tal

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#202]
På Lyttere nu siden vises der negative tal i antal minutter en lytter har haft ringet op.
Det tyder på den trækker 61 minutter fra hver gang jeg ringer op.

Ved første opkald skrev den -61 minutter, ved andet opkald -122, ved tredje -183 osv.
Den tæller korrekt hvert minut, dog tæller den nedad mod 0 da det er negative tal.

**Comment by michaelkrog** [comment]
Hvilken browser oplevede du det i?

**Comment by xToMMeRx** [comment]
I både IE11 og Chrome.
Har lige testet igen, og det er konsekvent hver gang i begge browsere.

**Comment by michaelkrog** [comment]
Mystisk.

Jeg oplever det slet ikke i mit lokale miljø.
Jeg må prøve kigge på hvad der sker i testmiljøet.



Den søndag den 8. februar 2015 skrev xToMMeRx <notifications@github.com>:

**Comment by xToMMeRx** [comment]
Sig til hvis du mangler et login du kan teste med.

**Comment by michaelkrog** [comment]
Hej. :)

Du må meget gerne mail mig et login samt evt. telefonnummer jeg kan ringe til.

**Comment by michaelkrog** [comment]
Åååååååååh ja. Tidszoner! :)

__1:__
Kan det passe at vores testserver enten ikke kører med dansk tidszone eller at tiden går forkert på den?

__2:__
I forbindelse med https://github.com/DRB-IT/blacktiger-controller/issues/184 har jeg sørget for at feltet 'dateJoined' der følger på JoinEvents ud til browseren indeholder det faktiske tidspunkt for hvornår brugeren kom ind i møderummet. Men der mangler info om tidszone i det datostempel, så det vil med sikkerhed blive et problem på tværs af tidszoner.

Kan du tjekke 1, så løser jeg 2.

**Comment by xToMMeRx** [comment]
Ja, klokken på serveren er lidt over 1 time og 1 minut foran, så det stemmer med de 61 minutter jeg så på websiden.

Af en eller anden grund synkroniserer NTP ikke klokken på test. Det graver jeg I, men det vil selvfølgelig være et problem med forskellige tidszoner.

**Comment by michaelkrog** [comment]
Perfekt. Så ved vi da hvad det skyldes. :)

**Comment by michaelkrog** [comment]
Fikset i https://github.com/DRB-IT/blacktigerjs/issues/3

**Comment by michaelkrog** [comment]
Den nuværende implementation med et tidsstempel fra serveren om lytterens login i møderummet kræver at både servernes og browserens tid er korrekt indstillet, hvilket vi ikke kan være sikre på. 

Serveren skal derfor istedet udstille hvor lang tid personen har været på. Det kan klienten anvende til at sætte et tidstempel lokalt for hvornår brugeren kom og dermed få et tidsstempel der passer meget klientens ur.

**Comment by michaelkrog** [comment]
Tilrettet i DRB-IT/blacktigerjs#3 & DRB-IT/blacktiger#115

**Comment by xToMMeRx** [comment]
Det ser meget bedre ud nu :-)

Jeg kan dog fremprovokere problemet hvis jeg ændrer klokken på min klient pc efter at en lytter har ringet ind.
Altså når en lytter først ringer op, viser den korrekt 0 minutter uanset hvad klokken er på klient pc'en.
Hvis jeg så sætter klokken en time tilbage på min pc og refresher websiden, så viser den -60 minutter.

Jeg tvivler på om nogen nogensinde vil opleve det i praksis da det er en meget unormal situation. Men det tyder på at klienten ikke udelukkende benytter den information den får fra serveren om hvor lang tid klienten har været på som du beskriver.

**Comment by michaelkrog** [comment]
Det skyldes at klienten regner tidstemplet ud lokalt og derefter gemmer det i historikken. Når du så justerer tiden og genindlæser bliver det dette tidstempel brugt i udregningen af hvor lang tid brugeren har været på.

Det burde aldrig ske i en virkelig situation.

**Comment by xToMMeRx** [comment]
Bortset fra i den situation at en klient pc's ur ikke passer og windows så automatisk synkroniserer tiden under mødet. ;-)

Men lad os lade den ligge, for det bliver nok aldrig/meget sjældent et problem i virkeligheden.
Hvis det gør kan vi altid tage den op igen.
