### ISSUE TITLE
"Ønsker at svare" bevæger sig ikke mere, og bjælke i toppen er forsvundet.

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#203]
Når "Ønsker at svare" teksten bliver vist ud for en lytter, dukkede der førhen en bjælke op i toppen af skærmen, denne kommer ikke frem på den nye version.

Derudover er "Ønsker at svare" teksten helt stillestående. Den rokker ikke længere frem og tilbage som tidligere, så man lægger ikke så nemt mærke til den som før.

**Comment by michaelkrog** [comment]
Bjælken i toppen: Denne fungerer fint i min Chrome og Safari. Er det IE du oplever det i?

Denne har jeg fikset lokalt nu. Committer det.

**Comment by xToMMeRx** [comment]
Jeg har lige prøvet igen I bade IE11 og Chrome.
Bjælken I toppen af skærmen dukker korrekt op, men teksten ud for selve lyttere "rokker" ikke fra side til side, hverken I IE eller Chome

**Comment by michaelkrog** [comment]
Super.. Så blev det faktisk fikset med https://github.com/DRB-IT/blacktiger-controller/commit/f4d049e08258bfa32be4cb5d799112118c4eca49
