### ISSUE TITLE
Fejlbeskeder via blacktiger-controller virker kun med DK label

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#205]
Hvis jeg laver et issue I blacktiger-production og giver det labelsne "public" og "DK" så bliver fejlbeskeden vist I alle lande, uanset om jeg bruger dk, no eller se domænenavn.

Hvis jeg bruger "public" og "NO" eller "SE" I blacktiger-production så bliver fejlbeskeden aldrig vist hverken I no eller se.

**Comment by michaelkrog** [comment]
I testmiljøet ser domænerne sådan her ud, ik?
* test.dk.telesal.org
* test.se.telesal.org
* test.no.telesal.org
osv.

Hvis det er korrekt, så tror jeg problemet er at den altid tager den første del af domænenavnet som land og evt. falder tilbage til dk. I dette tilfælde bliver det så altid 'test' der er landekode – med fallback til 'dk'.

**Comment by xToMMeRx** [comment]
Jo det er korrekt.
