### ISSUE TITLE
Blocked hos api.github.com

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#214]
Efter at have testet lidt på fejlbeskeder fra blacktiger-production med 3 browsere åben på én gang stødte jeg pludselig på at fejlbeskederne ikke blev opdateret.

Jeg forsøgte så at tilgå https://api.github.com/repos/DRB-IT/blacktiger-production manuelt og fik følgende besked:

{
  "message": "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

Hvis jeg oplever dette problem med 3 browsere åbne, så vil de også opleve problemet i komplekser med 3 sale. Måske endda steder med 2 sale, da jeg oplevede det allerede indenfor 15 minutter

**Comment by xToMMeRx** [comment]
Hvor tit sender du en request til api.github.com?
For det undrer mig lidt at det lykkedes mig at blive blocked (60 requests per time) på kun 15 minutter med 3 browsere.

**Comment by michaelkrog** [comment]
Den står stadig til at opdatere én gang i minuttet eller når man skifter lidt i menuen. https://github.com/DRB-IT/blacktiger-controller/issues/210 giver mulighed for at ændre det når den er løst.

Jeg kan prøve at ændre den til 5 minutter som vi talte om. Så kan vi når https://github.com/DRB-IT/blacktiger-controller/issues/210 justere videre på det.

**Comment by xToMMeRx** [comment]
Jeg kan ikke forstå at jeg har været 20 minutter om at teste det, men det må jeg jo have så.
Jeg tester videre senere, når jeg er unblocked igen.

5 minutter burde også være acceptabelt, og så burde der ikke være nogen der rammer blockeringen.
