### ISSUE TITLE
Når en sal ringer til det forkerte møderum optræder de med lyn-ikon

### ISSUE THREAD

**Issue by michaelkrog** [DRB-IT/blacktiger-controller#218]
@paf skrev:
>En ny variant – de har tilsyneladende prøvet at ringe fra sal B (+354 546 4607) til sal A i Reykjavík.
Lynet vises vel fordi det bagvedliggende nummer er Hxxx-xxx i stedet for Lxxxxxxx…

![unnamed](https://cloud.githubusercontent.com/assets/681472/6425532/01099cc6-bf2e-11e4-8052-90220f7e13a0.png)

**Comment by xToMMeRx** [comment]
Denne skal selvfølgelig vise pc symbolet som med en Lxxxx lytter.
Det behøver faktisk ikke være en fejl, der er nogle sale som af og til ringer en anden sal op og lytter med der, hvis de f.eks. ikke har noget foredragsholder.
