### ISSUE TITLE
"Første opkald" bliver ikke sat korrekt efter tryk på "Ryd historik"

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#220]
Hvis en lytter ringer op første gang kl. 16.00 og lægger på igen, så viser historikken korrekt at lytterens første opkald var kl. 16.00.
Hvis lytteren så ringer op anden gang kl. 16:10 og jeg mens lytteren er forbundet trykker "Ryd historik", så nulstiller live viewet korrekt til 1 opkald og antal minutter for det opkald.
Men når lytteren afbryder opkaldet står der at første kald var kl. 16.00 I historikken. Her burde den jo skrive 16.10, da jeg har ryddet historikken for det første kald.

**Comment by michaelkrog** [comment]
Afventer rettelse i blacktigerjs: https://github.com/DRB-IT/blacktigerjs/issues/22

**Comment by michaelkrog** [comment]
Fixed i DRB-IT/blacktigerjs#22
