### ISSUE TITLE
"Jeg ønsker at svare!" forsvinder ikke på andre enheder når man åbner mikrofonen

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#221]
Når en markerer og "Jeg ønsker at svare!" beskeden vises på skærmen, forsvinder teksten korrekt igen i det øjeblik man åbner for svarmikrofonen, så der kun står "Svar-mikrofonen er åben!".

Det sker dog kun på den enhed man åbner mikrofonen fra.
Hvis man har en tablet ved podiet, og man åbner svarmikrofonen fra pc'en med mixer pulten, så bliver både "Svar-mikrofonen er åben!" og "Jeg ønsker at svare!" teksterne ved med at stå på tabletten.

Dette må gerne synkronisere på lignende måde med når man ændrer navnet på én enhed så ændres den øjeblikkeligt på de andre.

**Comment by michaelkrog** [comment]
Afventer https://github.com/DRB-IT/blacktigerjs/issues/18

**Comment by michaelkrog** [comment]
Fixet i DRB-IT/blacktigerjs#18
