### ISSUE TITLE
Normalisering af navne er lidt for restriktiv

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#222]
Blacktiger-controller normaliserer automatisk navne så lille begyndelsesbogstav f.eks. rettes til stort begyndelsesbogstav - og det er meget fint.

Man skal dog kunne rette det tilbage hvis man ikke ønskede den ændring som normaliseringen lavede.
Hvis jeg f.eks. stiller mig foran F'et i "Thomas Frederiksen", og trykker backspace (for at erstatte det med et lille f), så rettes R'et til stort, og curseren flyttes til enden af linjen.
Det er ikke hensigtsmæssigt.

**Comment by xToMMeRx** [comment]
Nu retter den slet ikke til stort begyndelsesbogstav. Hvis jeg sletter hele navnet og skriver fornavn og efternavn med små bogstaver forbliver de små.

**Comment by michaelkrog** [comment]
Hvis du sletter navnet, forlader feltet og giver feltet fokus igen, virker det da korrekt?

Jeg tror det bunder i at jeg er usikker på hvornår små bogstaver skal tillades. Jeg forstod at man skal kunne ændre et bogstav der automatisk blev stort til et lille bogstav. Men hvad er så reglen hvor at længere skal kunne det?

Eksempel: 

michael von krog bliver til Michael Von Krog. Jeg skal så kunne gå tilbage og lave Von om til von. Men hvornår skal den ikke længere tillade at jeg laver store begyndelsesbogstaver om?

**Comment by xToMMeRx** [comment]
Ja, hvis jeg sletter navnet, forlader feltet og skriver et navn igen så skriver den korrekt stort begyndelsesbogstav.

Det kunne være smart hvis det fungerer som i f.eks. Word hvor den altid ændrer til stort, men man kan rette det til lille. Jeg ved ikke præcis hvad regelen er for hvornår de gør det og ikke gør det.

Det er ihvertfald ikke smart at den kun gør det når man har forladt feltet. For hvis nogen har skrevet forkert navn på en person og skal rette det, vil de jo ikke klikke ud af feltet inden de skriver et nyt navn.

Kunne man sige noget med at hvis man skriver et helt ord så retter den det til stort, men hvis man kun retter et bogstav så gør den ikke?

**Comment by michaelkrog** [comment]
Hmm.  Jo, det er nok noget med hvor meget man retter der afgør det.

Jeg leger lidt videre med det.

**Comment by michaelkrog** [comment]
Jeg har ændret det til at have følgende opførsel:

1. Formateringen til store forbogstaver er som udgangspunkt altid slået til.
2. Backspace og pil (venstre højre) slår formateringen fra.
3. Formateringen bliver enabled igen efter 2 tastetryk der ikke er backspace eller pil venstre/højre

__Eksempel 1:__
Jeg skriver `joakim von and`som automatisk bliver formateret til `Joakim Von And`. Jeg vil gerne tilbage og ændre `Von`til `von`så jeg bruger derfor `pil venstre`(som disabler formateringen), sletter `V`og skriver `v`istedet. Dette bliver ikke formatteret, fordi formateringen er disabled.

__Eksempel 2:__
Jeg skriver `john såmewon doe` som automatisk bliver til `John Såmewon Doe`. Jeg kommer i tanke om at det staves `Someone`og ikke `Såmewon`. Jeg går derfor tilbage med `pil venstre`(disabler formatering) og sletter `Såmewon`. Jeg begynder derefter at skrive `someone` og efter jeg har skrevet `som`(2 tastetryk) enables formateringen igen og laver det om til `Som`. Jeg kan færdiggøre det jeg skriver så der kommer til at stå `John Someone Doe`.

**Comment by xToMMeRx** [comment]
Hvad så hvis jeg bruger musen og klikker for at placere cursoren lige inden eller lige efter bogstavet jeg vil rette og trykker backspace eller del for at rette det?

**Comment by michaelkrog** [comment]
Det virker hvis man sætter cursoren og trykker backspace, fordi backspace er en af de tastetryk der slår formateringen fra. Jeg kan tilføje DEL, så vil det også virke den vej.

**Comment by xToMMeRx** [comment]
Ja det vil være en fin løsning
