### ISSUE TITLE
Websiden skriver den åbner svar-mikrofonen selvom lytteren er i lobby

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#223]
Hvis lyttere har ringet op, og man fra salen har glemt at ringe op, skjules svar-ikonet på hver lytter korrekt.
Hvis en lytter der hører vente-musik markerer at vedkommende gerne vil svare og man fra websiden trykker på "Jeg vil gerne svare!" teksten, så skriver websiden at svar-mikrofonen er åben hvilket ikke er korrekt da man ikke kan åbne en svarmikrofon så længe salen ikke har ringet op.

Jeg synes den skal blive ved med at vise hvis nogen markerer selvom der ikke er nogen sal på, men hvis man trykker på "Jeg vil gerne svare!" og der ikke er nogen sal på, skal der bare ikke ske noget. Den skal bare ignorere at man trykkede.

**Comment by michaelkrog** [comment]
Afventer https://github.com/DRB-IT/blacktigerjs/issues/19

**Comment by michaelkrog** [comment]
Fixet i blacktigerjs: DRB-IT/blacktigerjs#19
