### ISSUE TITLE
Hvornår skal CommentRequestEvent sendes?

### ISSUE THREAD

**Issue by michaelkrog** [DRB-IT/blacktiger-controller#225]
@paf61 @xToMMeRx 

Når man trykker 1 sendes et CommentRequestEvent og når der trykkes 0 sendes der CommentRequestCancelEvent ud. Det sker på baggrund af et DtmfEvent der modtages fra Asterisk.

Spørgsmålet er:
Hvornår skal CommentRequestEvent/CommentRequestCancelEvent sendes? Når DtmfTonen starter eller når den slutter?

Indtil har den blot været sendt når den slutter og det gør nok heller ikke den store forskel om det er det ene eller det andet. Jeg vil blot lige bringe det op, så vi for god ordens skyld kan tage kollektiv stilling til det.

**Comment by xToMMeRx** [comment]
Jeg vil mene at det er mest korrekt at den gør som den har gjort indtil nu - når DtmfTonen slutter.
På den måde dukker den ikke op ved et uheld hvis en knap på en telefon hænger, da der aldrig kommer en Dtmf end event.

**Comment by michaelkrog** [comment]
Super. Jeg lader den være.
