### ISSUE TITLE
Sprogvælger alfabetisk

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger-controller#230]
Sprogvælger i GUI bør være alfabetisk, sorteret efter sproget før parentesen.

**Comment by xToMMeRx** [comment]
Det ser ud til at du har fået sorteret på sproget i parantesen istedet for sproget før parantesen som paf61 nævnte. Den bør sortere på sproget før parantesen (hvad sproget hedder på sproget selv)

**Comment by michaelkrog** [comment]
Tricky :)

Den originale issuetekst jeg fik på mail lød:
```
Sprogvælger i GUI bør være alfabetisk, sorteret efter sproget i parentes.
```

Jeg retter til. ;)

**Comment by xToMMeRx** [comment]
Ah.. Paf må have indset at det var forkert og rettet beskeden på github 😉
