### ISSUE TITLE
Knapper såsom "åben mikrofon" hopper ned på næste linje ved smalt browser vindue

### ISSUE THREAD

**Issue by xToMMeRx** [DRB-IT/blacktiger-controller#233]
Både den blå "ønsker at svare" tekst og åben mikrofon knappen ude til højre, hopper ned på næste linje hvis man gør browser vinduet tilpas smalt.

Det giver et problem hvis man har sin web browser i en helt bestemt bredde, for når den blå tekst så bevæger sig hopper åben mikrofon ikonet op og ned mellem linje 1 og linje 2 så den er svær at trykke på/ramme. (Se mail d. 16/7-2015)

**Comment by michaelkrog** [comment]
Jeg har forsøgt mig frem med minimale ændringer til layoutet. Jeg har flyttet alle elementer der optræder i navnekolonnen(f.eks. 'Jeg vil svare'-labelen) frem før navnet, så de dukker op uanset hvor smal kollonnen.

Følgende er eksempler i 3 størrelser i forbindelse med når der er en der vil svare:
![skaermbillede 2015-07-21 kl 10 08 59](https://cloud.githubusercontent.com/assets/681472/8795876/f0f92cba-2f90-11e5-8c49-ec6dd6b0cf66.png)
![skaermbillede 2015-07-21 kl 10 09 21](https://cloud.githubusercontent.com/assets/681472/8795877/f0fe7562-2f90-11e5-8c7f-547fe296e51c.png)
![skaermbillede 2015-07-21 kl 10 09 40](https://cloud.githubusercontent.com/assets/681472/8795878/f0ff06e4-2f90-11e5-9ea8-18d80b69ea23.png)

**Comment by xToMMeRx** [comment]
Problemet er ikke så meget teksten "Jeg vil gerne svare", men mere selve knappen med samme function ude til højre. (Taleboblen).
Det er denne som skal forblive så samme linje og ikke må hoppe ned på en ny linje.

**Comment by michaelkrog** [comment]
Ok. Men vi er nok nødt til at lave 'jeg svarer' animationen om så. F.eks. til en glow-effekt(fade ind og ud). 

Hvis jeg ikke låser cellen til én linie, så vil den nuværende bevægelse ændre på bredden af cellens indhold og det vil forårsage et linieskift der hopper i bestemte opløsninger. Hvis animationen istedet for er en der ikke ændrer på bredden af cellens indhold, så skulle det gerne afhjælpe det.

**Comment by xToMMeRx** [comment]
Er det ikke muligt at låse højre kolonne (den med knapperne) så den altid har en fast defineret bredde, så det kun er den midterste kolonne der ombrydes til en linje mere hvis det ikke kan være der?

**Comment by michaelkrog** [comment]
Jo, det er det. Men hvis den midterste kolonne står og skifter/hopper, så skubber der resten af tabellen. Og er der så 2 eller flere der gerne vil svare samtidigt, så er problemet blot rykket længere ned i tabellen.

Det slår mig dog lige nu, at jeg nok godt kan reservere hele den plads som 'jeg vil svare' optager i forbindelse med den animerer, så vi stadig har ombrydning i den midterste kolonne, men vi i det mindste ikke risikerer at den hopper i forbindelse med den animerer.

Det prøver jeg lige.

**Comment by michaelkrog** [comment]
Dermed kommer det til at se sådan her ud:
![skaermbillede 2015-07-21 kl 10 42 58](https://cloud.githubusercontent.com/assets/681472/8796543/c4c674c2-2f95-11e5-9f37-12a4be3df172.png)
![skaermbillede 2015-07-21 kl 10 43 16](https://cloud.githubusercontent.com/assets/681472/8796542/c4c246ae-2f95-11e5-8f2f-5b8aee6ed25a.png)
![skaermbillede 2015-07-21 kl 10 45 59](https://cloud.githubusercontent.com/assets/681472/8796541/c4c17abc-2f95-11e5-9340-a98fce013c02.png)
