### ISSUE TITLE
Admin-side der viser sale og kontaktpersoner

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger-controller#83]
Jeg har i SQL lavet SEARCH_HALL der skal bruges til en side hvor man kan liste sale og kontaktpersoner. På siden skal være et enkelt søgefelt og en søg-knap. Outputtet bør være i en form så man kan copy/paste det til fx Excel og det pænt i kolonner.

**Comment by michaelkrog** [comment]
Flyttet til https://github.com/DRB-IT/blacktiger-admin/issues/5
