### ISSUE TITLE
Admin-side til at opdatere data for sale

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger-controller#84]
Der skal være en admin-side hvor man kan opdatere data for sale. I øjeblikket er det kun et kommentarfelt der skal kunne opdateres, det er nok for nuværende. Resten kan brugerne jo selv opdatere fra salen.

Der skal være et inputfelt til salens sip-id og en ok-knap. Herfra vises salens data ved sat kalde GET_HALL_INFO.
Der promptes nu for at udfylde et kommentarfelt, og ved tryk på ok kaldes UPDATE_ADMIN_COMMENT.
Herefter kaldes GET_HALL_INFO igen så man kan se at kommentaren er ændret og gemt.

**Comment by michaelkrog** [comment]
Flytte til https://github.com/DRB-IT/blacktiger-admin/issues/4
